### ISSUE TITLE
ValueError in pyart.retrieve.map_profile_to_gates

### ISSUE THREAD

**Issue by vlouf** [ARM-DOE/pyart#749]
Error when using `pyart.retrieve.map_profile_to_gates`

```python
Traceback (most recent call last):
  File "/miniconda3/envs/radar/lib/python3.6/site-packages/cpol_processing-1.0-py3.6.egg/cpol_processing/processing/radar_codes.py", line 454, in snr_and_sounding
    radar)
  File "/miniconda3/envs/radar/lib/python3.6/site-packages/pyart/retrieve/gate_id.py", line 74, in map_profile_to_gates
    fld = np.ma.masked_equal(f_interp(z + radar.altitude['data'][0]),
  File "/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/_lib/_util.py", line 236, in _asarray_validated
    raise ValueError('masked arrays are not supported')
ValueError: masked arrays are not supported
```

I have this error with 2 different versions of scipy, 1.0.0 and 1.1.0

**Comment by vlouf** [comment]
More details:
```python
ValueError                                Traceback (most recent call last)
<ipython-input-44-d46e0cfba1f5> in <module>()
----> 1 pyart.retrieve.map_profile_to_gates(temperatures, my_profile['height'].filled(np.NaN), radar)

/miniconda3/envs/radar/lib/python3.6/site-packages/pyart/retrieve/gate_id.py in map_profile_to_gates(profile, heights, radar, toa, profile_field, height_field)
     72         heights[:toa], profile[:toa], bounds_error=False,
     73         fill_value=get_fillvalue())
---> 74     fld = np.ma.masked_equal(f_interp(z + radar.altitude['data'][0]),
     75                              get_fillvalue())
     76 

/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     76 
     77         """
---> 78         x, x_shape = self._prepare_x(x)
     79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)

/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/interpolate/polyint.py in _prepare_x(self, x)
     88     def _prepare_x(self, x):
     89         """Reshape input x array to 1-D"""
---> 90         x = _asarray_validated(x, check_finite=False, as_inexact=True)
     91         x_shape = x.shape
     92         return x.ravel(), x_shape

/miniconda3/envs/radar/lib/python3.6/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    234     if not mask_ok:
    235         if np.ma.isMaskedArray(a):
--> 236             raise ValueError('masked arrays are not supported')
    237     toarray = np.asarray_chkfinite if check_finite else np.asarray
    238     a = toarray(a)

ValueError: masked arrays are not supported
```

I tried to specifically send them ndarray, and not masked array, but it doesn't work.

**Comment by vlouf** [comment]
Found the error l:60 in pyart/retrieve/gate_id.py:
`_, _, z = antenna_to_cartesian(rg / 1000.0, azg, eleg)`

`z` is a MaskedArray. So unmasking it correct this error.
